services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: cycleeye-analysis
    
    ports:
      - "8501:8501"
    
    volumes:
      - ./data:/app/data
      - ./assets:/app/assets
    
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    
    restart: "no"